version: "3.4"

services:
  ros:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/achillesrasquinha/ros
    ports:
      - "3000:5000"
    volumes:
      - ./workspace:/home/ros/ros_ws